remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
- jekyll-include-cache

baseurl: /portfolio
title: Portfolio

relative_links:
  enabled: true
  collections: true
  
include:
  - README.md
  # - personal portfolio.html
