remote_theme: pages-themes/cayman@v0.2.0
plugins:
# - jekyll-remote-theme
- jekyll-paginate
baseurl: /portfolio
title: Portfolio

relative_links:
  enabled: true
  collections: true
  
include:
  - README.md
  # - personal portfolio.html
