remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
baseurl: /personal portfolio.html
title: Portfolio

relative_links:
  enabled: true
  collections: true
  
include:
  # - README.md
  - personal portfolio.html
