remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme

baseurl: /portfolio
title: Portfolio

relative_links:
  enabled: true
  collections: true
  
include:
  - README.md
  # - personal portfolio.html
