remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

baseurl: /portfolio
title: Vivek Patel
description: Data Analyst | Data Scientist | NLP Engineer 
show_downloads: true

relative_links:
  enabled: true
  collections: true
  
include:
  - README.md
